language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  - OCAML_VERSION=4.08 PACKAGE="l2"
  - OCAML_VERSION=4.09 PACKAGE="l2"
os:
  - linux
